import Vue from "vue";
import {
  Button,
  Input,
  Container,
  Header,
  Main,
  Footer,
  Cascader,
  Menu,
  Submenu,
  Loading,
  Table,
  TableColumn,
  Pagination,
  Form,
  Select,
  Checkbox,
  Radio,
  Switch,
  DatePicker,
  TimePicker,
  RadioGroup,
  CheckboxGroup,
  Row,
  Col,
  FormItem,
  Option,
  Upload,
  Dialog,
  Link,
  Image,
  Breadcrumb,
  BreadcrumbItem,
  CarouselItem
} from "element-ui";
Vue.use(Link);
Vue.use(Image);
Vue.use(Dialog);
Vue.use(Select);
Vue.use(Option);
Vue.use(Upload);
Vue.use(FormItem);
Vue.use(Row);
Vue.use(Col);
Vue.use(CheckboxGroup);
Vue.use(Radio);
Vue.use(Button);
Vue.use(RadioGroup);
Vue.use(Checkbox);
Vue.use(Switch);
Vue.use(CarouselItem);
Vue.use(DatePicker);
Vue.use(TimePicker);
Vue.use(Input);
Vue.use(Container);
Vue.use(Header);
Vue.use(Main);
Vue.use(Footer);
Vue.use(Cascader);
Vue.use(Menu);
Vue.use(Submenu);
Vue.use(Loading);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Pagination);
Vue.use(Form);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);
